configfile: "config/config.yaml"


import pandas as pd

samples_df = pd.read_table(config["samples"]).set_index("sample", drop=False)
SAMPLES = list(samples_df['sample'])
reference_path = config["reference_path"]
reference_seqdict = reference_path.replace('.fasta', '.dict')

rule all:
    input:
        bamdedupindex=expand("results/DedupReads/{sample}_aln_marked.bam.bai", sample=SAMPLES),
        samtoolsreferenceindex = config["reference_path"] + ".fai",
        #gatk_depth_summary=expand("results/DedupReads/{sample}_depth_of_coverage", sample=SAMPLES),
        #mergedvcf=expand("results/MergedVCF/{sample}_all_merged.vcf", sample=SAMPLES),
        instrain_out=expand("results/instrain/{sample}_instrain", sample=SAMPLES),

# delete everything so we can re-run things
rule clean:
    shell: 'rm -r results/*'

# Add Modular rules
include: "rules/kneaddata.smk"
include: "rules/trim.smk"
include: "rules/bowtie.smk"
include: "rules/gatk.smk"
include: "rules/samtools.smk"
include: "rules/freebayes.smk"
include: "rules/instrain.smk"
