samples: config/samples.tsv
fastq_dir: /nfs/turbo/umms-esnitkin/Project_Cdiff/Sequence_data/2022_03_24_Cdiff_Population/
#fastq_dir: /scratch/esnitkin_root/esnitkin/apirani/Project_Cdiff/Analysis/Project_U01_SB/2021_09_07_Strainest_Mixed_Strain_Simulation

ncores: 4

# Command line parameters for rule trimmomatic_pe - trimmomatic.smk
adapter_file: config/adapters/NexteraPE-PE.fa
seed_mismatches: 2
palindrome_clipthreshold: 30
simple_clipthreshold: 10
minadapterlength: 8
keep_both_reads: true
window_size: 4
window_size_quality: 20
minlength: 40
headcrop_length: 0

# Reference Genome Settings
reference_path: resources/cdiff_630.fasta
reference_stb: resources/cdiff_630.stb

# Human Bowtie2 index
hgbtdb: resources/kneaddata/hg37dec_v0.1 
