samples: config/samples.tsv
fastq_dir: /nfs/esnitkin/Project_VRE_metagenomics_analysis/Sequence_data/fastq/3381-CB/fastqs_3381-CB
#fastq_dir: /nfs/turbo/umms-esnitkin/Project_VRE_metagenomics_analysis/Analysis/2021_06_25_LDV_Simulation/Simulated_data/test_data

# Command line parameters for rule trimmomatic_pe - trimmomatic.smk
adapter_file: /config/adapters/NexteraPE-PE.fa
seed_mismatches: 2
palindrome_clipthreshold: 30
simple_clipthreshold: 10
minadapterlength: 8
keep_both_reads: true
window_size: 4
window_size_quality: 20
minlength: 40
headcrop_length: 0

# Reference Genome Settings
reference_path: resources/cdiff_630.fasta
reference_stb: resources/cdiff_630.stb
